local NavigationCost = dofile("core/intelligence/learning/navigation_cost.lua")
local TacticalMemory = dofile("core/intelligence/learning/tactical_memory.lua")
local LatencyClassifier = dofile("core/intelligence/learning/latency_classifier.lua")
local Quality = dofile("core/intelligence/learning/observation_quality.lua")
local Counters = dofile("core/intelligence/learning/horizon_counters.lua")

describe("intelligence bounded adaptive memory", function()
  it("keeps navigation learning additive, bounded, decayed, and advisory", function()
    local costs = NavigationCost.new({ decayMs = 100, maxCost = 5 })
    assert.equals(2, costs:observe("tile", 4, 0.5, 0))
    assert.equals(5, costs:observe("tile", 9, 1, 0))
    assert.equals(2.5, costs:get("tile", 50))
    assert.equals(0, costs:get("tile", 100))
  end)

  it("expires and deterministically compacts tactical memory", function()
    local memory = TacticalMemory.new({ maxEntries = 2, ttlMs = 100 })
    memory:remember("b", 2, 0); memory:remember("a", 1, 0); memory:remember("c", 3, 1)
    assert.is_nil(memory:get("a", 1))
    assert.equals(2, memory:get("b", 1))
    assert.is_nil(memory:get("b", 100))
  end)

  it("classifies latency and clamps adapted thresholds", function()
    local latency = LatencyClassifier.new({ goodMs = 100, poorMs = 250, alpha = 1 })
    assert.equals("good", latency:observe(80))
    assert.equals("degraded", latency:observe(150))
    assert.equals("poor", latency:observe(300))
    assert.equals(400, latency:threshold(200, 2, 400))
  end)

  it("weights observation evidence by quality and freshness", function()
    assert.equals(0.2, Quality.weight({ confidence = 0.8, completeness = 0.5, timestamp = 0 }, 50, 100))
    assert.equals(0, Quality.weight({ confidence = 1, timestamp = 0 }, 100, 100))
  end)

  it("separates and bounds learning horizons", function()
    local counters = Counters.new({ immediate = 2, combat = 3, route = 4, session = 5 })
    counters:add("hits", 4)
    assert.same({ 2, 3, 4, 4 }, {
      counters:get("hits", "immediate"), counters:get("hits", "combat"),
      counters:get("hits", "route"), counters:get("hits", "session")
    })
    counters:reset("combat")
    assert.equals(0, counters:get("hits", "combat"))
    assert.equals(4, counters:get("hits", "route"))
  end)
end)
