local ContextAdjustment = dofile("core/intelligence/learning/context_adjustment.lua")

describe("context-scoped intelligence adjustment", function()
  it("stays advisory until enough evidence and clamps its contribution", function()
    local contexts = ContextAdjustment.new({ minSamples = 30, minConfidence = 0.7, maxAdjustment = 0.1 })
    for index = 1, 29 do contexts:observe("route|Dragon", true, index) end
    local adjustment, evidence = contexts:get("route|Dragon")
    assert.equals(0, adjustment)
    assert.is_false(evidence.actionable)
    contexts:observe("route|Dragon", true, 30)
    adjustment, evidence = contexts:get("route|Dragon")
    assert.is_true(evidence.actionable)
    assert.is_true(adjustment > 0 and adjustment <= 0.1)
    assert.equals(0, contexts:get("other-route|Dragon"))
  end)

  it("persists bounded summaries and rejects incompatible state", function()
    local contexts = ContextAdjustment.new({ maxContexts = 2, minSamples = 1 })
    contexts:observe("old", false, 1)
    contexts:observe("middle", true, 2)
    contexts:observe("new", true, 3)
    assert.equals(0, contexts:get("old"))
    local restored = ContextAdjustment.new({ maxContexts = 2, minSamples = 1 })
    assert.is_true(restored:restore(contexts:serialize()))
    assert.is_false(restored:restore({ schemaVersion = 2, contexts = {} }))
  end)
end)
