local KillSwitch = dofile("core/intelligence/guardrails/kill_switch.lua")

describe("intelligence kill switch", function()
  it("starts with all scopes enabled", function()
    local sw = KillSwitch.new()
    assert.is_false(sw:isEnabled("global"))
    assert.is_false(sw:isEnabled("model:test"))
    assert.is_false(sw:isEnabled("character:player1"))
  end)

  it("enables/disables global scope", function()
    local sw = KillSwitch.new()
    sw:enable("global")
    assert.is_true(sw:isEnabled("global"))
    sw:disable("global")
    assert.is_false(sw:isEnabled("global"))
  end)

  it("enables/disables per scope independently", function()
    local sw = KillSwitch.new()
    sw:enable("model:combat")
    assert.is_true(sw:isEnabled("model:combat"))
    assert.is_false(sw:isEnabled("model:exploration"))
    sw:enable("character:knight")
    assert.is_true(sw:isEnabled("character:knight"))
    sw:disable("model:combat")
    assert.is_false(sw:isEnabled("model:combat"))
    assert.is_true(sw:isEnabled("character:knight"))
  end)

  it("returns status of all disabled scopes", function()
    local sw = KillSwitch.new()
    sw:enable("global")
    sw:enable("route:forest")
    local status = sw:getStatus()
    assert.is_true(status["global"])
    assert.is_true(status["route:forest"])
    assert.is_nil(status["model:test"])
  end)

  it("global disable overrides per-scope", function()
    local sw = KillSwitch.new()
    sw:enable("model:combat")
    sw:enable("global")
    assert.is_true(sw:isEnabled("model:combat"))
    assert.is_true(sw:isEnabled("global"))
    sw:disable("model:combat")
    assert.is_true(sw:isEnabled("model:combat"))
  end)
end)
