describe("intelligence model catalog prior", function()
  it("uses a neutral prior for fresh predictions", function()
    local Catalog = dofile("core/intelligence/learning/model_catalog.lua")
    local registry = Catalog.registerAll()
    local prediction = registry:predict("LatencyModel")
    assert.equals(0.5, prediction.probability)
    assert.is_truthy(prediction.explanation)
  end)
end)
