local Models = dofile("core/intelligence/learning/online_models.lua")

describe("intelligence online models", function()
  it("updates bounded streaming statistics", function()
    local ewma = Models.ewma(0.5)
    assert.equals(10, ewma:update(10))
    assert.equals(15, ewma:update(20))

    local variance = Models.welford()
    variance:update(1); variance:update(2); variance:update(3)
    assert.equals(2, variance.mean)
    assert.equals(1, variance:variance())

    local beta = Models.beta()
    beta:update(true, 1); beta:update(false, 1)
    assert.equals(0.5, beta:mean())
    assert.equals(2, beta.samples)
  end)

  it("bounds Markov states and predicts deterministically", function()
    local model = Models.markov(2)
    model:observe("idle", "wave")
    model:observe("idle", "melee")
    model:observe("idle", "wave")
    model:observe("wave", "idle")
    model:observe("other", "ignored")
    assert.equals("wave", model:predict("idle").state)
    assert.equals(2 / 3, model:predict("idle").probability)
    assert.is_nil(model:predict("other"))
  end)
end)
