local Budget = dofile("core/intelligence/foundation/performance_budget.lua")

describe("intelligence performance budget", function()
  it("degrades optional work in deterministic order", function()
    local budget = Budget.new(5)
    assert.equals("diagnostics", budget:record(6))
    assert.is_false(budget:enabled("diagnostics"))
    assert.equals("replay", budget:record(7))
    assert.equals("learning", budget:record(8))
    assert.equals("neuralModel", budget:record(9))
    assert.equals("routeAlternatives", budget:record(10))
    assert.is_nil(budget:record(11))
    assert.is_true(budget:enabled("safety"))
  end)
end)
