local Normalizer = dofile("core/intelligence/learning/reward_normalizer.lua")

describe("intelligence reward normalizer", function()
  it("normalizes a reward vector using z-score", function()
    local norm = Normalizer.new({ windowSize = 100 })
    -- Feed known values to set stats
    for i = 1, 20 do
      norm:updateStats({ version = 1, timestamp = i, components = { xp = 10, safety = 5 } })
    end
    local result = norm:normalize({ version = 1, timestamp = 21, components = { xp = 10, safety = 5 } })
    assert.is_table(result)
    assert.is_table(result.components)
    -- All zeros since value == mean
    assert.equals(0, result.components.xp)
    assert.equals(0, result.components.safety)
  end)

  it("clamps extreme values to [-1, 1]", function()
    local norm = Normalizer.new({ windowSize = 100 })
    norm:updateStats({ version = 1, timestamp = 1, components = { xp = 10 } })
    norm:updateStats({ version = 1, timestamp = 2, components = { xp = 12 } })
    local result = norm:normalize({ version = 1, timestamp = 3, components = { xp = 99999 } })
    assert.equals(1, result.components.xp)
    local result2 = norm:normalize({ version = 1, timestamp = 4, components = { xp = -99999 } })
    assert.equals(-1, result2.components.xp)
  end)

  it("returns 0 for zero standard deviation", function()
    local norm = Normalizer.new({ windowSize = 100 })
    norm:updateStats({ version = 1, timestamp = 1, components = { xp = 5 } })
    norm:updateStats({ version = 1, timestamp = 2, components = { xp = 5 } })
    local result = norm:normalize({ version = 1, timestamp = 3, components = { xp = 5 } })
    assert.equals(0, result.components.xp)
  end)

  it("updates statistics correctly", function()
    local norm = Normalizer.new({ windowSize = 100 })
    norm:updateStats({ version = 1, timestamp = 1, components = { xp = 10, safety = 2 } })
    norm:updateStats({ version = 1, timestamp = 2, components = { xp = 20, safety = 4 } })
    local stats = norm:getStats()
    assert.is_table(stats)
    assert.equals(2, stats.count)
    assert.near(15, stats.mean.xp, 0.001)
    assert.near(3, stats.mean.safety, 0.001)
  end)

  it("returns default stats before any observations", function()
    local norm = Normalizer.new()
    local stats = norm:getStats()
    assert.equals(0, stats.count)
  end)

  it("respects window size limit", function()
    local norm = Normalizer.new({ windowSize = 3 })
    norm:updateStats({ version = 1, timestamp = 1, components = { xp = 1 } })
    norm:updateStats({ version = 1, timestamp = 2, components = { xp = 2 } })
    norm:updateStats({ version = 1, timestamp = 3, components = { xp = 100 } })
    norm:updateStats({ version = 1, timestamp = 4, components = { xp = 4 } })
    local stats = norm:getStats()
    -- Window of 3: should only include last 3 values (2, 100, 4)
    assert.equals(3, stats.count)
    assert.near(35.333333333333, stats.mean.xp, 0.001)
  end)

  it("uses default config values", function()
    local norm = Normalizer.new()
    assert.is_table(norm)
    local stats = norm:getStats()
    assert.equals(0, stats.count)
  end)
end)
