local Guard = dofile("core/intelligence/guardrails/target_switch_guard.lua")

describe("intelligence target switch guard", function()
  it("creates with default config", function()
    local g = Guard.new()
    local stats = g:getStats()
    assert.equals(0, stats.switches)
    assert.equals(5, stats.window)
    assert.equals(0, stats.rate)
  end)

  it("creates with custom config", function()
    local g = Guard.new({ maxSwitchesPerWindow = 3, windowSeconds = 30, minHoldTime = 5 })
    local stats = g:getStats()
    assert.equals(0, stats.switches)
    assert.equals(3, stats.window)
    assert.equals(0, stats.rate)
  end)

  it("allows first switch", function()
    local g = Guard.new()
    assert.is_true(g:canSwitch({}))
  end)

  it("allows switches within rate limit", function()
    local g = Guard.new({ maxSwitchesPerWindow = 3, windowSeconds = 60 })
    for _ = 1, 3 do
      g:recordSwitch()
    end
    assert.is_false(g:canSwitch({}))
  end)

  it("blocks switches exceeding rate", function()
    local g = Guard.new({ maxSwitchesPerWindow = 2, windowSeconds = 60 })
    g:recordSwitch()
    g:recordSwitch()
    assert.is_false(g:canSwitch({}))
  end)

  it("respects hold time", function()
    local g = Guard.new({ minHoldTime = 5, maxSwitchesPerWindow = 10 })
    g:recordSwitch({ now = 0 })
    assert.is_false(g:canSwitch({ now = 0 }))
    assert.is_false(g:canSwitch({ now = 2 }))
    assert.is_true(g:canSwitch({ now = 5 }))
    assert.is_true(g:canSwitch({ now = 10 }))
  end)

  it("allows switch when hold time elapses", function()
    local g = Guard.new({ minHoldTime = 3, maxSwitchesPerWindow = 10 })
    g:recordSwitch({ now = 0 })
    assert.is_true(g:canSwitch({ now = 100 }))
  end)

  it("manual override bypasses rate limit", function()
    local g = Guard.new({ maxSwitchesPerWindow = 1, windowSeconds = 60 })
    g:recordSwitch({ now = 0 })
    assert.is_true(g:canSwitch({ now = 0, manualOverride = true }))
  end)

  it("returns correct stats", function()
    local g = Guard.new({ maxSwitchesPerWindow = 10, windowSeconds = 60 })
    g:recordSwitch()
    g:recordSwitch()
    local stats = g:getStats()
    assert.equals(2, stats.switches)
    assert.equals(10, stats.window)
  end)

  it("prunes old switches from window", function()
    local g = Guard.new({ maxSwitchesPerWindow = 2, windowSeconds = 10 })
    g:recordSwitch({ now = 1 })
    g:recordSwitch({ now = 2 })
    assert.is_false(g:canSwitch({ now = 3 }))
    assert.is_true(g:canSwitch({ now = 12 }))
  end)

  it("resets rate after window expires", function()
    local g = Guard.new({ maxSwitchesPerWindow = 1, windowSeconds = 5 })
    g:recordSwitch({ now = 0 })
    assert.is_false(g:canSwitch({ now = 0 }))
    assert.is_true(g:canSwitch({ now = 6 }))
    g:recordSwitch({ now = 6 })
    assert.is_false(g:canSwitch({ now = 6 }))
  end)

  it("blocks tiny score difference switches", function()
    local g = Guard.new({ maxSwitchesPerWindow = 10 })
    g:recordSwitch({ now = 0 })
    assert.is_false(g:canSwitch({ now = 0, scoreDiff = 0.01 }))
    assert.is_true(g:canSwitch({ now = 10, scoreDiff = 0.01 }))
  end)

  it("allows switch when near death", function()
    local g = Guard.new({ maxSwitchesPerWindow = 10 })
    g:recordSwitch({ now = 0 })
    assert.is_true(g:canSwitch({ now = 0, nearDeath = true, scoreDiff = 0.01 }))
  end)

  it("blocks learned switch after manual selection", function()
    local g = Guard.new({ manualLockWindow = 30, maxSwitchesPerWindow = 10 })
    g:recordManualSwitch({ now = 0 })
    assert.is_false(g:canSwitch({ now = 0 }))
    assert.is_false(g:canSwitch({ now = 29 }))
    assert.is_true(g:canSwitch({ now = 31 }))
  end)

  it("manual override bypasses all guards", function()
    local g = Guard.new({ maxSwitchesPerWindow = 1, windowSeconds = 60, minHoldTime = 100 })
    g:recordSwitch({ now = 0 })
    assert.is_true(g:canSwitch({ now = 0, manualOverride = true }))
  end)
end)
