local Session = dofile("core/intelligence/telemetry/session.lua")

describe("IntelligenceTelemetrySession", function()
  local session
  local fixedNow = 1700000000

  before_each(function()
    session = Session.new({ root = "/bot/Foo/telemetry/", now = function() return fixedNow end })
  end)

  describe("new", function()
    it("returns a new inactive instance", function()
      assert.is_not_nil(session)
      assert.is_false(session.active)
      assert.is_nil(session.sessionId)
      assert.is_nil(session.dir)
    end)

    it("uses defaults when config is empty", function()
      local defaultSession = Session.new()
      assert.is_not_nil(defaultSession)
      assert.is_false(defaultSession.active)
    end)

    it("exposes open, close, isActive, currentDir, manifest", function()
      assert.is_function(session.open)
      assert.is_function(session.close)
      assert.is_function(session.isActive)
      assert.is_function(session.currentDir)
      assert.is_function(session.manifest)
    end)
  end)

  describe("open", function()
    it("activates the session and computes dir", function()
      local ok, dir = session:open("s1", "char1")
      assert.is_true(ok)
      assert.equals("/bot/Foo/telemetry/" .. os.date("%Y-%m-%d", fixedNow) .. "/session-s1/", dir)
      assert.is_true(session:isActive())
      assert.equals("s1", session.sessionId)
      assert.equals("char1", session.characterScope)
      assert.equals(fixedNow, session.startedAt)
      assert.is_nil(session.endedAt)
      assert.is_nil(session.closeReason)
    end)

    it("defaults characterScope to empty string when not given", function()
      session:open("s1")
      assert.equals("", session.characterScope)
    end)

    it("rejects a nil sessionId without mutating state", function()
      local ok, err = session:open(nil)
      assert.is_false(ok)
      assert.equals("invalid_session_id", err)
      assert.is_false(session.active)
      assert.is_nil(session.sessionId)
    end)

    it("rejects an empty sessionId without mutating state", function()
      local ok, err = session:open("")
      assert.is_false(ok)
      assert.equals("invalid_session_id", err)
      assert.is_false(session.active)
    end)

    it("rejects a non-string sessionId without mutating state", function()
      local ok, err = session:open(123)
      assert.is_false(ok)
      assert.equals("invalid_session_id", err)
      assert.is_false(session.active)
    end)

    it("fails with already_active when opened twice without closing", function()
      session:open("s1")
      local ok, err = session:open("s2")
      assert.is_false(ok)
      assert.equals("already_active", err)
      assert.equals("s1", session.sessionId)
    end)
  end)

  describe("close", function()
    it("fails with not_active when closing without opening", function()
      local ok, err = session:close()
      assert.is_false(ok)
      assert.equals("not_active", err)
    end)

    it("deactivates and returns the manifest", function()
      session:open("s1")
      local ok, manifest = session:close("done")
      assert.is_true(ok)
      assert.is_false(session:isActive())
      assert.equals(fixedNow, session.endedAt)
      assert.equals("done", session.closeReason)
      assert.equals("done", manifest.closeReason)
      assert.is_false(manifest.active)
    end)

    it("defaults reason to unknown when not given", function()
      session:open("s1")
      session:close()
      assert.equals("unknown", session.closeReason)
    end)

    it("allows re-opening after close and produces a fresh startedAt and dir", function()
      session:open("s1")
      session:close("done")

      local laterNow = fixedNow + 86400
      session.now = function() return laterNow end

      local ok, dir = session:open("s2")
      assert.is_true(ok)
      assert.is_true(session:isActive())
      assert.equals("s2", session.sessionId)
      assert.equals(laterNow, session.startedAt)
      assert.is_nil(session.endedAt)
      assert.is_nil(session.closeReason)
      assert.equals("/bot/Foo/telemetry/" .. os.date("%Y-%m-%d", laterNow) .. "/session-s2/", dir)
    end)
  end)

  describe("isActive", function()
    it("returns false before open", function()
      assert.is_false(session:isActive())
    end)

    it("returns true after open and false after close", function()
      session:open("s1")
      assert.is_true(session:isActive())
      session:close()
      assert.is_false(session:isActive())
    end)
  end)

  describe("currentDir", function()
    it("returns nil before first open", function()
      assert.is_nil(session:currentDir())
    end)

    it("returns the computed dir after open", function()
      session:open("s1")
      assert.equals(session.dir, session:currentDir())
    end)
  end)

  describe("manifest", function()
    it("is callable before open with nil/false fields", function()
      local manifest = session:manifest()
      assert.equals(1, manifest.schemaVersion)
      assert.equals("1.0.0", manifest.collectorVersion)
      assert.equals("unknown", manifest.botVersion)
      assert.is_nil(manifest.sessionId)
      assert.is_nil(manifest.startedAt)
      assert.is_nil(manifest.endedAt)
      assert.is_nil(manifest.closeReason)
      assert.is_false(manifest.active)
    end)

    it("reflects state while active", function()
      session:open("s1", "char1")
      local manifest = session:manifest()
      assert.equals("s1", manifest.sessionId)
      assert.equals("char1", manifest.characterScope)
      assert.equals(fixedNow, manifest.startedAt)
      assert.is_nil(manifest.endedAt)
      assert.is_true(manifest.active)
    end)

    it("uses configured schemaVersion, collectorVersion, botVersion", function()
      local customSession = Session.new({
        schemaVersion = 2,
        collectorVersion = "2.3.4",
        botVersion = "5.6.7",
      })
      local manifest = customSession:manifest()
      assert.equals(2, manifest.schemaVersion)
      assert.equals("2.3.4", manifest.collectorVersion)
      assert.equals("5.6.7", manifest.botVersion)
    end)
  end)

  describe("global registration", function()
    it("sets nExBot.IntelligenceTelemetrySession", function()
      assert.is_not_nil(nExBot.IntelligenceTelemetrySession)
    end)
  end)
end)
