local StateEnums = {}

StateEnums.State = {
  UNBOUND = "UNBOUND",
  WAITING_FOR_CHARACTER = "WAITING_FOR_CHARACTER",
  BINDING = "BINDING",
  LOADING = "LOADING",
  MIGRATING = "MIGRATING",
  APPLYING_SILENTLY = "APPLYING_SILENTLY",
  READY = "READY",
  FLUSHING = "FLUSHING",
  ERROR_RECOVERABLE = "ERROR_RECOVERABLE",
}

StateEnums.Origin = {
  USER = "USER",
  INITIAL_RESTORE = "INITIAL_RESTORE",
  RECONNECT_RESTORE = "RECONNECT_RESTORE",
  CHARACTER_SWITCH = "CHARACTER_SWITCH",
  ROOT_PROFILE_SWITCH = "ROOT_PROFILE_SWITCH",
  MODULE_PROFILE_SWITCH = "MODULE_PROFILE_SWITCH",
  MIGRATION = "MIGRATION",
  SAFETY_INHIBIT = "SAFETY_INHIBIT",
  DEPENDENCY_INHIBIT = "DEPENDENCY_INHIBIT",
  RECOVERY = "RECOVERY",
  TEST = "TEST",
}

StateEnums.Inhibitor = {
  DISCONNECTED = "DISCONNECTED",
  PROFILE_APPLY = "PROFILE_APPLY",
  SAFETY = "SAFETY",
  DEPENDENCY_NOT_READY = "DEPENDENCY_NOT_READY",
  ERROR = "ERROR",
}

nExBot = nExBot or {}
nExBot.StateEnums = StateEnums

return StateEnums