local Identity = dofile("core/containers/identity.lua")

describe("Identity", function()
  it("creates unique identities", function()
    local id1 = Identity.make(1, "mainBackpack", "none", 0, 3003, "v1")
    local id2 = Identity.make(1, "mainBackpack", "none", 1, 3003, "v1")
    assert.not_equals(id1, id2)
  end)

  it("creates different identities across generations", function()
    local id1 = Identity.make(1, "mainBackpack", "none", 0, 3003, "v1")
    local id2 = Identity.make(2, "mainBackpack", "none", 0, 3003, "v1")
    assert.not_equals(id1, id2)
  end)

  it("parses identity components", function()
    local id = Identity.make(12, "mainBackpack", "none", 0, 3003, "v3")
    local parts = Identity.parse(id)
    assert.equals(12, parts.generation)
    assert.equals("mainBackpack", parts.rootKind)
    assert.equals("none", parts.parentId)
    assert.equals(0, parts.slotIndex)
    assert.equals(3003, parts.itemType)
    assert.equals("v3", parts.version)
  end)

  it("matches identity fields", function()
    local id = Identity.make(12, "mainBackpack", "none", 0, 3003, "v3")
    assert.is_true(Identity.matches(id, { generation = 12 }))
    assert.is_true(Identity.matches(id, { rootKind = "mainBackpack" }))
    assert.is_false(Identity.matches(id, { generation = 13 }))
  end)
end)
