local Queue = dofile("core/containers/queue.lua")

describe("Queue", function()
  it("preserves FIFO order", function()
    local q = Queue.new(10)
    q:enqueue("a")
    q:enqueue("b")
    q:enqueue("c")
    assert.equals("a", q:dequeue())
    assert.equals("b", q:dequeue())
    assert.equals("c", q:dequeue())
  end)

  it("returns nil when empty", function()
    local q = Queue.new(10)
    assert.is_nil(q:dequeue())
  end)

  it("reports size correctly", function()
    local q = Queue.new(10)
    assert.equals(0, q.size)
    q:enqueue("a")
    assert.equals(1, q.size)
    q:dequeue()
    assert.equals(0, q.size)
  end)

  it("rejects when full", function()
    local q = Queue.new(2)
    assert.is_true(q:enqueue("a"))
    assert.is_true(q:enqueue("b"))
    assert.is_false(q:enqueue("c"))
    assert.equals(2, q.size)
  end)

  it("peeks without removing", function()
    local q = Queue.new(10)
    q:enqueue("a")
    assert.equals("a", q:peek())
    assert.equals(1, q.size)
  end)

  it("compacts correctly", function()
    local q = Queue.new(100)
    for i = 1, 50 do q:enqueue(i) end
    for i = 1, 40 do q:dequeue() end
    q:compact()
    assert.equals(10, q.size)
    assert.equals(1, q.head)
    assert.equals(10, q.tail)
    assert.equals(41, q:dequeue())
  end)

  it("clears all items", function()
    local q = Queue.new(10)
    q:enqueue("a")
    q:enqueue("b")
    q:clear()
    assert.equals(0, q.size)
    assert.is_nil(q:dequeue())
  end)
end)
