local Readiness = dofile("core/containers/readiness.lua")
local Registry = dofile("core/containers/registry.lua")

describe("Readiness", function()
  it("computes ready when empty (nothing to do)", function()
    local reg = Registry.new()
    local r = Readiness.compute(reg, 1, false)
    assert.equals("ready", r.status)
    assert.equals(1, r.generation)
  end)

  it("computes discovering when queuing", function()
    local reg = Registry.new()
    reg:add({ identity = "a", state = "queued", itemType = 3003 })
    local r = Readiness.compute(reg, 1, false)
    assert.equals("discovering", r.status)
    assert.equals(1, r.queuedCount)
  end)

  it("computes ready when all inspected", function()
    local reg = Registry.new()
    reg:add({ identity = "a", state = "inspected", itemType = 3003 })
    local r = Readiness.compute(reg, 1, false)
    assert.equals("ready", r.status)
    assert.equals(1, r.inspectedCount)
  end)

  it("computes degraded when some failed", function()
    local reg = Registry.new()
    reg:add({ identity = "a", state = "inspected", itemType = 3003 })
    reg:add({ identity = "b", state = "failed", itemType = 3031 })
    local r = Readiness.compute(reg, 1, false)
    assert.equals("degraded", r.status)
    assert.equals(1, r.failedCount)
  end)

  it("marks mainBackpackReady when inspected", function()
    local reg = Registry.new()
    reg:add({ identity = "a", state = "inspected", itemType = 3003 })
    local r = Readiness.compute(reg, 1, false)
    assert.is_true(r.mainBackpackReady)
  end)

  it("sets quiverRequired for paladins", function()
    local reg = Registry.new()
    local r = Readiness.compute(reg, 1, true)
    assert.is_true(r.quiverRequired)
  end)

  it("sets quiverRequired false for non-paladins", function()
    local reg = Registry.new()
    local r = Readiness.compute(reg, 1, false)
    assert.is_false(r.quiverRequired)
  end)
end)
