local Registry = dofile("core/containers/registry.lua")

describe("Registry", function()
  it("adds and retrieves candidates", function()
    local reg = Registry.new()
    local candidate = {
      identity = "1:mainBackpack:none:0:3003:v1",
      state = "discovered",
      itemType = 3003,
    }
    reg:add(candidate)
    assert.equals(candidate, reg:get("1:mainBackpack:none:0:3003:v1"))
  end)

  it("counts by state", function()
    local reg = Registry.new()
    reg:add({ identity = "a", state = "queued", itemType = 3003 })
    reg:add({ identity = "b", state = "queued", itemType = 3003 })
    reg:add({ identity = "c", state = "opened", itemType = 3003 })
    assert.equals(2, reg:countByState("queued"))
    assert.equals(1, reg:countByState("opened"))
  end)

  it("finds items by type", function()
    local reg = Registry.new()
    reg:add({ identity = "a", state = "inspected", itemType = 3003 })
    reg:add({ identity = "b", state = "inspected", itemType = 3031 })
    local results = reg:findByItemType(3003)
    assert.equals(1, #results)
    assert.equals("a", results[1].identity)
  end)

  it("manages parent-child relationships", function()
    local reg = Registry.new()
    reg:add({ identity = "parent", state = "inspected", itemType = 3003 })
    reg:add({ identity = "child1", state = "discovered", itemType = 3031 })
    reg:add({ identity = "child2", state = "discovered", itemType = 3031 })
    reg:setParent("parent", "child1")
    reg:setParent("parent", "child2")
    local children = reg:getChildren("parent")
    assert.equals(2, #children)
  end)

  it("removes candidates correctly", function()
    local reg = Registry.new()
    reg:add({ identity = "a", state = "queued", itemType = 3003 })
    reg:remove("a")
    assert.is_nil(reg:get("a"))
    assert.equals(0, reg:countByState("queued"))
  end)

  it("transitions state correctly", function()
    local reg = Registry.new()
    reg:add({ identity = "a", state = "discovered", itemType = 3003 })
    reg:setState("a", "queued")
    assert.equals(0, reg:countByState("discovered"))
    assert.equals(1, reg:countByState("queued"))
  end)

  it("handles three identical backpacks as distinct", function()
    local reg = Registry.new()
    reg:add({ identity = "1:main:none:0:3003:v1", state = "inspected", itemType = 3003 })
    reg:add({ identity = "1:main:none:1:3003:v1", state = "inspected", itemType = 3003 })
    reg:add({ identity = "1:main:none:2:3003:v1", state = "inspected", itemType = 3003 })
    local results = reg:findByItemType(3003)
    assert.equals(3, #results)
  end)

  it("clears all state", function()
    local reg = Registry.new()
    reg:add({ identity = "a", state = "queued", itemType = 3003 })
    reg:add({ identity = "b", state = "opened", itemType = 3031 })
    reg:setParent("a", "b")
    reg:clear()
    assert.equals(0, reg:countByState("queued"))
    assert.is_nil(reg:get("a"))
    assert.is_nil(reg:get("b"))
  end)
end)
