local StateMachine = dofile("core/containers/state_machine.lua")

describe("StateMachine", function()
  it("starts in IDLE", function()
    local sm = StateMachine.new()
    assert.equals("idle", sm.state)
  end)

  it("transitions from IDLE to WAITING_FOR_SESSION", function()
    local sm = StateMachine.new()
    assert.is_true(sm:canTransition("waitingForSession"))
    assert.is_true(sm:transition("waitingForSession"))
    assert.equals("waitingForSession", sm.state)
  end)

  it("rejects invalid transitions", function()
    local sm = StateMachine.new()
    assert.is_false(sm:canTransition("traversing"))
    assert.is_false(sm:transition("traversing"))
    assert.equals("idle", sm.state)
  end)

  it("allows CANCELLED from any state", function()
    local sm = StateMachine.new()
    assert.is_true(sm:canTransition("cancelled"))
    assert.is_true(sm:transition("cancelled"))
    assert.equals("cancelled", sm.state)
  end)

  it("allows FAILED from any state", function()
    local sm = StateMachine.new()
    assert.is_true(sm:canTransition("failed"))
    assert.is_true(sm:transition("failed"))
    assert.equals("failed", sm.state)
  end)

  it("increments generation on cancel", function()
    local sm = StateMachine.new()
    local gen1 = sm.generation
    sm:transition("cancelled")
    assert.equals(gen1 + 1, sm.generation)
  end)

  it("follows valid traversal path", function()
    local sm = StateMachine.new()
    assert.is_true(sm:transition("waitingForSession"))
    assert.is_true(sm:transition("discoveringRoots"))
    assert.is_true(sm:transition("reconciling"))
    assert.is_true(sm:transition("traversing"))
    assert.is_true(sm:transition("waitingForAcknowledgement"))
    assert.is_true(sm:transition("traversing"))
    assert.is_true(sm:transition("completed"))
    assert.equals("completed", sm.state)
  end)

  it("handles pause for critical action", function()
    local sm = StateMachine.new()
    sm:transition("waitingForSession")
    sm:transition("discoveringRoots")
    sm:transition("reconciling")
    sm:transition("traversing")
    assert.is_true(sm:canTransition("pausedForCriticalAction"))
    sm:transition("pausedForCriticalAction")
    assert.is_true(sm:canTransition("traversing"))
    sm:transition("traversing")
    assert.equals("traversing", sm.state)
  end)

  it("handles page wait", function()
    local sm = StateMachine.new()
    sm:transition("waitingForSession")
    sm:transition("discoveringRoots")
    sm:transition("reconciling")
    sm:transition("traversing")
    sm:transition("waitingForAcknowledgement")
    assert.is_true(sm:canTransition("waitingForPage"))
    sm:transition("waitingForPage")
    assert.is_true(sm:canTransition("traversing"))
    sm:transition("traversing")
    assert.equals("traversing", sm.state)
  end)

  it("handles recovery from failure", function()
    local sm = StateMachine.new()
    sm:transition("failed")
    assert.is_true(sm:canTransition("recovering"))
    sm:transition("recovering")
    assert.is_true(sm:canTransition("idle"))
    sm:transition("idle")
    assert.equals("idle", sm.state)
  end)

  it("handles degraded to traversing", function()
    local sm = StateMachine.new()
    sm:transition("waitingForSession")
    sm:transition("discoveringRoots")
    sm:transition("reconciling")
    sm:transition("traversing")
    sm:transition("completed")
    assert.is_true(sm:canTransition("degraded"))
    sm:transition("degraded")
    assert.is_true(sm:canTransition("traversing"))
    sm:transition("traversing")
    assert.equals("traversing", sm.state)
  end)

  it("increments generation on each cancel", function()
    local sm = StateMachine.new()
    local gen1 = sm.generation
    sm:transition("cancelled")
    local gen2 = sm.generation
    sm:transition("idle")
    sm:transition("cancelled")
    local gen3 = sm.generation
    assert.equals(gen1 + 1, gen2)
    assert.equals(gen2 + 1, gen3)
  end)
end)
