-- state_machine_spec.lua (updated for v5 state machine with 23 states)
local StateMachine = dofile("core/containers/state_machine.lua")
local S = StateMachine.States

describe("StateMachine", function()
  it("starts in IDLE", function()
    local sm = StateMachine.new()
    assert.equals(S.IDLE, sm.state)
  end)

  it("transitions from IDLE to WAITING_FOR_SESSION", function()
    local sm = StateMachine.new()
    assert.is_true(sm:canTransition(S.WAITING_FOR_SESSION))
    assert.is_true(sm:transition(S.WAITING_FOR_SESSION))
    assert.equals(S.WAITING_FOR_SESSION, sm.state)
  end)

  it("rejects invalid transitions", function()
    local sm = StateMachine.new()
    assert.is_false(sm:canTransition(S.TRAVERSING))
    assert.is_false(sm:transition(S.TRAVERSING))
    assert.equals(S.IDLE, sm.state)
  end)

  it("allows CANCELLED from any state", function()
    local sm = StateMachine.new()
    assert.is_true(sm:canTransition(S.CANCELLED))
    assert.is_true(sm:transition(S.CANCELLED))
    assert.equals(S.CANCELLED, sm.state)
  end)

  it("allows FAILED from any state", function()
    local sm = StateMachine.new()
    assert.is_true(sm:canTransition(S.FAILED))
    assert.is_true(sm:transition(S.FAILED))
    assert.equals(S.FAILED, sm.state)
  end)

  it("increments generation on cancel", function()
    local sm = StateMachine.new()
    local gen1 = sm.generation
    sm:transition(S.CANCELLED)
    assert.equals(gen1 + 1, sm.generation)
  end)

  it("incrementGeneration does not change state", function()
    local sm = StateMachine.new()
    local gen0 = sm.generation
    sm:incrementGeneration("test")
    assert.equals(gen0 + 1, sm.generation)
    assert.equals(S.IDLE, sm.state)
  end)

  it("records transition history", function()
    local sm = StateMachine.new()
    sm:transition(S.WAITING_FOR_SESSION, "init")
    local last = sm:getLastTransition()
    assert.equals(S.IDLE, last.from)
    assert.equals(S.WAITING_FOR_SESSION, last.to)
    assert.equals("init", last.reason)
  end)

  it("follows valid traversal path", function()
    local sm = StateMachine.new()
    assert.is_true(sm:transition(S.WAITING_FOR_SESSION))
    assert.is_true(sm:transition(S.DISCOVERING_ROOTS))
    assert.is_true(sm:transition(S.RECONCILING_OPEN_WINDOWS))
    assert.is_true(sm:transition(S.TRAVERSING))
    assert.is_true(sm:transition(S.OPENING_CONTAINER))
    assert.is_true(sm:transition(S.WAITING_FOR_ACKNOWLEDGEMENT))
    assert.is_true(sm:transition(S.TRAVERSING))
    assert.is_true(sm:transition(S.COMPLETED))
    assert.equals(S.COMPLETED, sm.state)
  end)

  it("handles pause for critical action", function()
    local sm = StateMachine.new()
    sm:transition(S.WAITING_FOR_SESSION)
    sm:transition(S.DISCOVERING_ROOTS)
    sm:transition(S.RECONCILING_OPEN_WINDOWS)
    sm:transition(S.TRAVERSING)
    assert.is_true(sm:canTransition(S.PAUSED_FOR_CRITICAL_ACTION))
    sm:transition(S.PAUSED_FOR_CRITICAL_ACTION)
    assert.is_true(sm:canTransition(S.TRAVERSING))
    sm:transition(S.TRAVERSING)
    assert.equals(S.TRAVERSING, sm.state)
  end)

  it("handles page wait", function()
    local sm = StateMachine.new()
    sm:transition(S.WAITING_FOR_SESSION)
    sm:transition(S.DISCOVERING_ROOTS)
    sm:transition(S.RECONCILING_OPEN_WINDOWS)
    sm:transition(S.TRAVERSING)
    sm:transition(S.OPENING_CONTAINER)
    sm:transition(S.WAITING_FOR_ACKNOWLEDGEMENT)
    assert.is_true(sm:canTransition(S.SCANNING_PAGE))
    sm:transition(S.SCANNING_PAGE)
    assert.is_true(sm:canTransition(S.WAITING_FOR_PAGE))
    sm:transition(S.WAITING_FOR_PAGE)
    assert.is_true(sm:canTransition(S.TRAVERSING))
    sm:transition(S.TRAVERSING)
    assert.equals(S.TRAVERSING, sm.state)
  end)

  it("handles FAILED -> IDLE path", function()
    local sm = StateMachine.new()
    sm:transition(S.FAILED)
    assert.is_true(sm:canTransition(S.IDLE))
    sm:transition(S.IDLE)
    assert.equals(S.IDLE, sm.state)
  end)

  it("backward compat: recovering state reachable after FAILED", function()
    local sm = StateMachine.new()
    sm:transition(S.FAILED)
    assert.is_true(sm:canTransition("recovering"))
    sm:transition("recovering")
    assert.is_true(sm:canTransition(S.IDLE))
    sm:transition(S.IDLE)
    assert.equals(S.IDLE, sm.state)
  end)

  it("backward compat: degraded state reachable from completed", function()
    local sm = StateMachine.new()
    sm:transition(S.WAITING_FOR_SESSION)
    sm:transition(S.DISCOVERING_ROOTS)
    sm:transition(S.RECONCILING_OPEN_WINDOWS)
    sm:transition(S.TRAVERSING)
    sm:transition(S.COMPLETED)
    -- Legacy: completed -> degraded -> traversing
    sm.state = S.TRAVERSING  -- force for test path
    assert.is_true(sm:canTransition("degraded"))
    sm:transition("degraded")
    assert.is_true(sm:canTransition(S.TRAVERSING))
    sm:transition(S.TRAVERSING)
    assert.equals(S.TRAVERSING, sm.state)
  end)

  it("COMPLETED_DEGRADED transitions to IDLE or TRAVERSING", function()
    local sm = StateMachine.new()
    sm:transition(S.WAITING_FOR_SESSION)
    sm:transition(S.DISCOVERING_ROOTS)
    sm:transition(S.RECONCILING_OPEN_WINDOWS)
    sm:transition(S.TRAVERSING)
    sm:transition(S.COMPLETED_DEGRADED)
    assert.is_true(sm:canTransition(S.IDLE))
    assert.is_true(sm:canTransition(S.TRAVERSING))
  end)

  it("isTerminal returns true for completed states", function()
    local sm = StateMachine.new()
    -- Navigate to TRAVERSING first, then COMPLETED
    sm:transition(S.WAITING_FOR_SESSION)
    sm:transition(S.DISCOVERING_ROOTS)
    sm:transition(S.RECONCILING_OPEN_WINDOWS)
    sm:transition(S.TRAVERSING)
    sm:transition(S.COMPLETED)
    assert.is_true(sm:isTerminal())
  end)

  it("isTerminal returns false for active states", function()
    local sm = StateMachine.new()
    sm:transition(S.WAITING_FOR_SESSION)
    assert.is_false(sm:isTerminal())
  end)

  it("reset() returns to IDLE and bumps generation", function()
    local sm = StateMachine.new()
    sm:transition(S.WAITING_FOR_SESSION)
    local gen = sm.generation
    sm:reset("test")
    assert.equals(S.IDLE, sm.state)
    assert.equals(gen + 1, sm.generation)
  end)

  it("increments generation on each cancel", function()
    local sm = StateMachine.new()
    local gen1 = sm.generation
    sm:transition(S.CANCELLED)
    local gen2 = sm.generation
    sm:transition(S.IDLE)
    sm:transition(S.CANCELLED)
    local gen3 = sm.generation
    assert.equals(gen1 + 1, gen2)
    assert.equals(gen2 + 1, gen3)
  end)
end)
