local attack_analytics = require("core.attack.attack_analytics")

describe("attack_analytics", function()
  before_each(function()
    attack_analytics.resetAnalytics()
  end)

  it("starts with zero counts", function()
    local stats = attack_analytics.getAnalytics()
    assert.equals(0, stats.totalAttacks)
    assert.equals(0, stats.empowerments)
  end)

  it("records spell use", function()
    attack_analytics.recordSpellUse("exori gran")
    local stats = attack_analytics.getAnalytics()
    assert.equals(1, stats.totalAttacks)
    assert.equals(1, stats.spells["exori gran"])
  end)

  it("records multiple spell uses", function()
    attack_analytics.recordSpellUse("exori gran")
    attack_analytics.recordSpellUse("exori gran")
    attack_analytics.recordSpellUse("exori vis")
    local stats = attack_analytics.getAnalytics()
    assert.equals(3, stats.totalAttacks)
    assert.equals(2, stats.spells["exori gran"])
    assert.equals(1, stats.spells["exori vis"])
  end)

  it("records rune use", function()
    attack_analytics.recordRuneUse("3161")
    local stats = attack_analytics.getAnalytics()
    assert.equals(1, stats.totalAttacks)
    assert.equals(1, stats.runes["3161"])
  end)

  it("records buff use without double-counting totalAttacks", function()
    -- recordBuffUse is always called after recordSpellUse
    attack_analytics.recordSpellUse("utito tempo")
    attack_analytics.recordBuffUse("utito tempo")
    local stats = attack_analytics.getAnalytics()
    assert.equals(1, stats.totalAttacks)
    assert.equals(1, stats.empowerments)
    assert.equals(1, stats.spells["utito tempo"])
  end)

  it("resets analytics", function()
    attack_analytics.recordSpellUse("exori gran")
    attack_analytics.recordRuneUse("3161")
    attack_analytics.resetAnalytics()
    local stats = attack_analytics.getAnalytics()
    assert.equals(0, stats.totalAttacks)
    assert.equals(0, stats.empowerments)
  end)
end)
