describe("ReachabilityState", function()
  local RS

  before_each(function()
    _G.ReachabilityState = nil
    RS = dofile("targetbot/domain/reachability_states.lua")
  end)

  it("defines all required reachability states", function()
    assert.equals("ATTACKABLE_NOW", RS.ATTACKABLE_NOW)
    assert.equals("REPOSITION_REQUIRED", RS.REPOSITION_REQUIRED)
    assert.equals("TEMPORARILY_BLOCKED", RS.TEMPORARILY_BLOCKED)
    assert.equals("VISIBILITY_UNKNOWN", RS.VISIBILITY_UNKNOWN)
    assert.equals("PATH_API_UNAVAILABLE", RS.PATH_API_UNAVAILABLE)
    assert.equals("MOVING_TARGET", RS.MOVING_TARGET)
    assert.equals("DIFFERENT_FLOOR", RS.DIFFERENT_FLOOR)
    assert.equals("REMOVED", RS.REMOVED)
    assert.equals("CONFIRMED_HARD_UNREACHABLE", RS.CONFIRMED_HARD_UNREACHABLE)
  end)

  it("identifies hard release states", function()
    assert.is_true(RS.isHardRelease("DIFFERENT_FLOOR"))
    assert.is_true(RS.isHardRelease("REMOVED"))
    assert.is_true(RS.isHardRelease("CONFIRMED_HARD_UNREACHABLE"))
    assert.is_false(RS.isHardRelease("TEMPORARILY_BLOCKED"))
    assert.is_false(RS.isHardRelease("ATTACKABLE_NOW"))
    assert.is_false(RS.isHardRelease(nil))
  end)

  it("identifies temporary states", function()
    assert.is_true(RS.isTemporary("TEMPORARILY_BLOCKED"))
    assert.is_true(RS.isTemporary("VISIBILITY_UNKNOWN"))
    assert.is_true(RS.isTemporary("PATH_API_UNAVAILABLE"))
    assert.is_true(RS.isTemporary("MOVING_TARGET"))
    assert.is_true(RS.isTemporary("REPOSITION_REQUIRED"))
    assert.is_false(RS.isTemporary("ATTACKABLE_NOW"))
    assert.is_false(RS.isTemporary("DIFFERENT_FLOOR"))
    assert.is_false(RS.isTemporary("CONFIRMED_HARD_UNREACHABLE"))
  end)

  it("identifies attackable state", function()
    assert.is_true(RS.isAttackable("ATTACKABLE_NOW"))
    assert.is_false(RS.isAttackable("TEMPORARILY_BLOCKED"))
    assert.is_false(RS.isAttackable("REPOSITION_REQUIRED"))
    assert.is_false(RS.isAttackable(nil))
  end)
end)
